# ============================================================
# Ansible Role: mssql - Handlers
# ============================================================

- name: restart mssql
  ansible.windows.win_service:
    name: MSSQLSERVER
    state: restarted

- name: restart mssql agent
  ansible.windows.win_service:
    name: SQLSERVERAGENT
    state: restarted
