#!/bin/bash
# ============================================================
# Create Ansible Vault — SC MEDIA SRL
# Run on the jumphost AFTER infrastructure deployment.
#
# Fetches all secrets from Azure Key Vault (kv-mediasrl-persistent)
# using the jumphost's Managed Identity (no az login needed).
# Creates ~/.vault-pass and an encrypted group_vars/all/vault.yml.
#
# Usage (from jumphost):
#   cd ~/ansible-workspace
#   bash scripts/create-ansible-vault.sh
# ============================================================

set -euo pipefail

KV_NAME="kv-mediasrl-persistent"
VAULT_PASS_FILE="$HOME/.vault-pass"
VAULT_FILE="group_vars/all/vault.yml"

# ── Inline logging helpers ───────────────────────────────────
_C_CYAN='\033[0;36m'; _C_GREEN='\033[0;32m'; _C_RED='\033[0;31m'
_C_YELLOW='\033[1;33m'; _C_GRAY='\033[0;37m'; _C_BOLD='\033[1m'; _C_RST='\033[0m'
_LOG_OK=0; _LOG_FAIL=0; _LOG_WARN=0; _TS=$(date +%s)
LOG_DIR="${HOME}/logs"
mkdir -p "$LOG_DIR"
_LOG_FILE="$LOG_DIR/create-ansible-vault-$(date +%Y%m%d-%H%M%S).log"
exec > >(tee -a "$_LOG_FILE") 2>&1

log_header() { echo ""; echo -e "  ${_C_CYAN}┌─── $1${_C_RST}"; echo ""; }
log_step()   { echo -e "  ${_C_YELLOW}[>>] $*${_C_RST}"; }
log_ok()     { echo -e "  ${_C_GREEN}[OK] $*${_C_RST}"; _LOG_OK=$((_LOG_OK+1)); }
log_warn()   { echo -e "  ${_C_YELLOW}[!]  $*${_C_RST}"; _LOG_WARN=$((_LOG_WARN+1)); }
log_fail()   { echo -e "  ${_C_RED}[!!] $*${_C_RST}"; _LOG_FAIL=$((_LOG_FAIL+1)); }
log_info()   { echo -e "  ${_C_GRAY}     $*${_C_RST}"; }
# ─────────────────────────────────────────────────────────────

_SEP=$(printf '%.0s=' {1..60})
echo ""
echo -e "${_C_CYAN}  ${_SEP}${_C_RST}"
echo -e "${_C_BOLD}  SC MEDIA SRL — Ansible Vault Setup${_C_RST}"
echo -e "${_C_GRAY}  $(date '+%Y-%m-%d %H:%M:%S')  ·  Log: $(basename "$_LOG_FILE")${_C_RST}"
echo -e "${_C_CYAN}  ${_SEP}${_C_RST}"

log_header "Pregătire directoare"
mkdir -p "$(dirname "$VAULT_FILE")"
log_ok "Director group_vars/all pregătit"

log_header "Preluare secrete din Key Vault ($KV_NAME)"  # [1/4]
log_step "Conectare via Managed Identity (fără az login)..."

fetch_secret() {
    local secret_name="$1"
    az keyvault secret show \
        --vault-name "$KV_NAME" \
        --name "$secret_name" \
        --query value -o tsv 2>/dev/null \
    || { log_fail "Nu s-a putut prelua secretul '$secret_name'"; exit 1; }
}

VAULT_PASS=$(fetch_secret "ansible-vault-password")        && log_ok "ansible-vault-password"
VM_ADMIN_PASSWORD=$(fetch_secret "vm-admin-password")      && log_ok "vm-admin-password"
MYSQL_ROOT_PASSWORD=$(fetch_secret "mysql-root-password")  && log_ok "mysql-root-password"
MYSQL_WP_PASSWORD=$(fetch_secret "mysql-wordpress-password") && log_ok "mysql-wordpress-password"
MYSQL_MON_PASSWORD=$(fetch_secret "mysql-monitoring-password") && log_ok "mysql-monitoring-password"
MYSQL_API_PASSWORD=$(fetch_secret "mysql-api-password")    && log_ok "mysql-api-password"
WP_ADMIN_PASSWORD=$(fetch_secret "wordpress-admin-password") && log_ok "wordpress-admin-password"

log_header "Scriere fișier parolă Vault"  # [2/4]
printf '%s' "$VAULT_PASS" > "$VAULT_PASS_FILE"
chmod 600 "$VAULT_PASS_FILE"
log_ok "$VAULT_PASS_FILE (mode 600)"

log_header "Generare conținut Vault (plaintext temporar)"  # [3/4]

VAULT_TMP=$(mktemp)
trap 'rm -f "$VAULT_TMP"' EXIT

cat > "$VAULT_TMP" <<EOF
---
# Ansible Vault — SC MEDIA SRL
# Generated by scripts/create-ansible-vault.sh
# DO NOT commit this file unencrypted.
# Re-generate with: bash scripts/create-ansible-vault.sh

vault_admin_password: "${VM_ADMIN_PASSWORD}"
vault_mysql_root_password: "${MYSQL_ROOT_PASSWORD}"
vault_mysql_wordpress_password: "${MYSQL_WP_PASSWORD}"
vault_mysql_monitoring_password: "${MYSQL_MON_PASSWORD}"
vault_mysql_api_password: "${MYSQL_API_PASSWORD}"
vault_wordpress_admin_password: "${WP_ADMIN_PASSWORD}"
EOF
log_ok "Conținut vault generat (6 variabile)"

log_header "Criptare cu ansible-vault"  # [4/4]
ansible-vault encrypt "$VAULT_TMP" \
    --vault-password-file "$VAULT_PASS_FILE" \
    --output "$VAULT_FILE"
log_ok "$VAULT_FILE (criptat AES-256)"

# ── Rezumat final ────────────────────────────────────────────
_DUR=$(( $(date +%s) - _TS ))
echo ""
_STATUS_CLR=$([ "$_LOG_FAIL" -gt 0 ] && echo "$_C_RED" || echo "$_C_GREEN")
echo -e "${_STATUS_CLR}${_C_BOLD}  ${_SEP}${_C_RST}"
[ "$_LOG_FAIL" -gt 0 ] \
    && echo -e "${_C_RED}${_C_BOLD}  EXECUȚIE CU ERORI${_C_RST}" \
    || echo -e "${_C_GREEN}${_C_BOLD}  VAULT SETUP COMPLET${_C_RST}"
echo -e "  Durată : $((_DUR/60))m $((_DUR%60))s   |   OK: $_LOG_OK   FAIL: $_LOG_FAIL"
log_info "Vault file   : $VAULT_FILE"
log_info "Vault pass   : $VAULT_PASS_FILE  (mode 600)"
log_info "Ansible cfg  : vault_password_file = ~/.vault-pass"
log_info "Log          : $_LOG_FILE"
echo -e "${_STATUS_CLR}${_C_BOLD}  ${_SEP}${_C_RST}"
echo ""
